[package]
name = "card-counter"
version = "0.5.0"
authors = ["Justin Barclay <justincbarclay@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
reqwest = {version = "0.10.0", features = ["blocking", "json"]}
serde = {version = "1.0.104", features = ["derive"]}
tokio = { version = "0.2", features = ["macros"] }
serde_json = "1.0.45"
serde_yaml = "0.8.11"
regex = "1"
clap = "2.33.0"
dialoguer = "0.5.0"
dirs = "2.0"
prettytable-rs = "0.8"
error-chain = "0.12.1"

async-trait = "0.1.27"
rusoto_core = "0.43.0"
rusoto_dynamodb = "0.43.0"
serde_dynamodb = "0.5.0-beta.1"