name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        rust: [stable]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - os: macOS-latest
            rust: stable
            artifact_name: card-counter
            release_name: card-counter-darwin.zip
          - os: windows-latest
            rust: stable
            artifact_name: card-counter.exe
            release_name: card-counter-windows.zip
          - os: ubuntu-latest
            rust: stable
            artifact_name: card-counter
            release_name: card-counter-linux.zip
    steps:
      - name: Setup Rust
        uses: hecrj/setup-rust-action@master
        with:
          rust-version: ${{ matrix.rust }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build the crate for release
        run: cargo build --release
      - name: Run tests
        run: cargo test --verbose
      - name: Zip the executable on Mac
        if: matrix.os == 'macOS-latest'
        run: zip ${{ matrix.release_name }} target/release/${{ matrix.artifact_name }}
      - name: Zip the executable
        if: matrix.os != 'macOS-latest'
        run: 7z a -tzip ${{ matrix.release_name }} target/release/${{ matrix.artifact_name }}
      - name: Upload libraries to GitHub release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.release_name }}
          asset_name: ${{ matrix.release_name }}
          tag: ${{ github.ref }}
